version: '3'

services:
    # Python with Jupyter
    dev:
        build:
            context: ..
            dockerfile: .devcontainer/dev.Dockerfile
            args:
                VARIANT: "3.9"
                NODE_VERSION: "none"
        env_file:
            - ../.env
        ports:
            - 9090:8080
        volumes:
            - ..:/workspace:cached
        # Overrides default command so things don't shut down after the process ends.
        command: sleep infinity